FROM node:20-bookworm

WORKDIR /app

RUN mkdir -p /app && chown -R 1000:1000 /app

COPY --chown=1000:1000 package*.json ./
RUN npm ci --omit=dev --omit=optional

COPY --chown=1000:1000 src/ui.js ./
COPY --chown=1000:1000 public ./public
EXPOSE 3002

USER 1000

CMD ["node", "ui.js"]

